# fly.toml app configuration file generated for staging-dt-17-7-1-1721226316-client on 2024-07-17T14:26:07Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'staging-dt-17-7-1-1721226316-client'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
